
DROP TABLE CALENDAR
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CAL;

CREATE TABLE CALENDAR(
    
   SEQ NUMBER(8) PRIMARY KEY,
   ID VARCHAR2(50) NOT NULL,
   TITLE VARCHAR2(200) NOT NULL,
   CONTENT VARCHAR2(4000) NOT NULL,
   RDATE VARCHAR2(12) NOT NULL,
   WDATE DATE NOT NULL
);


CREATE SEQUENCE SEQ_CAL
START WITH 1
INCREMENT BY 1;

ALTER TABLE CALENDAR
ADD CONSTRAINT FK_CAL_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);



SELECT SEQ, ID, TITLE, CONTENT, RDATE, WDATE
FROM ( 
      SELECT ROW_NUMBER()OVER(PARTITION BY SUBSTR(RDATE, 1, 8)ORDER BY RDATE ASC) AS RNUM,  
              SEQ, ID, TITLE, CONTENT, RDATE, WDATE
              FROM CALENDAR
              WHERE ID='aaa' AND SUBSTR(RDATE, 1, 6)='202006'
      )    
      WHERE RNUM BETWEEN 1 AND 5
      
      
       -- WHERE ID='aaa' AND SUBSTR(RDATE, 1, 6)='202005'  SUBSTR(RDATE, 1, 8)= '20200518'


SELECT SEQ, ID, TITLE, CONTENT, RDATE, WDATE
FROM CALENDAR
WHERE SEQ=1




UPDATE CALENDAR
SET TITLE = '초코파이', CONTENT = 'CHOCOLATE', WDATE= SYSDATE
WHERE ID = 'aaa'
AND SEQ = 2














